# Generated by Django 5.1.1 on 2024-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
